### ISSUE TITLE
Redis persistence error.

### ISSUE THREAD

**Issue by liuzhaowei55** [khs1994-docker/lnmp#110]
### 操作系统

* [x] Linux
  * [x] CentOS

### Docker 版本

* [x] Stable ( 17.09.1-ce)

### 问题描述

Hi，你好，我根据你的这个配置文件自己做了一些修改在使用Redis时遇到一些问题：
```
MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```
Redis使用一段时间会报这个问题无法持久化，我删除容器使用重新开一个容器扔使用仪器的数据卷，Redis 上边也会保存有一部分的数据，只是最新的数据会丢失，你遇到这个问题了吗？

**Comment by khs1994** [comment]
`redis` 配置文件改了吗

**Comment by khs1994** [comment]
网上搜一下报错信息的相关结果，或者从 `./logs/redis/redis.log`  中找一下信息，我没遇到过。

我搜了一下，有的是因为内存不够。

**Comment by liuzhaowei55** [comment]
@khs1994 我大概找到问题了，因为我的 redis 没有设置密码，而且 6379 端口暴露出来了，所以被别人扫描了，然后有人 hack 的话，为了获取权限会操作持久化文件，就导致我的服务断掉了，还好这个服务是跑在 docker 中，主机看了一下没有问题。
