### ISSUE TITLE
ERROR  Check docker-compose error

### ISSUE THREAD

**Issue by whcoding** [khs1994-docker/lnmp#1195]
docker Version:  20.10.8
Docker Compose Version: v2.0.0-rc.1

问题1: git clone master 分支 执行 ./lnmp-docker up 会报 WARNING 让我切换到 20.10  执行 ./lnmp-docker checkout 会循环这个错误

问题2: 手动clone 20.10 分支 执行 ./lnmp-docker up 会报错 ERROR  Check docker-compose error

**Comment by khs1994** [comment]
系统版本
