### ISSUE TITLE
支持的软件中缺少`pm2`啊

### ISSUE THREAD

**Issue by cgfeel** [khs1994-docker/lnmp#1225]
我是`laravel`使用者，看了遍简介，发现少了`pm2`，这样`laravel`队列和异步事件就没办法支持了

这是`pm2`官方发布的，在docker下集成的方法：
> https://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/
---

另外我想问问能否提供一个一套plugin的机制方便第三方添加软件或者修改配置呢？我看简介里这样说：
> 除了 `.env` 等特定文件，本项目中的任何文件严禁二次修改。

**Comment by khs1994** [comment]
没必要在 PHP 中引入 node, 容器中方案采用 s6 来运行多任务

**Comment by khs1994** [comment]
* https://docs.lnmp.khs1994.com/custom.html
