### ISSUE TITLE
关于在`laravel`项目中生成的日志权限问题

### ISSUE THREAD

**Issue by cgfeel** [khs1994-docker/lnmp#1230]
在`laravel`项目自动生成的日志`./app/api_service/storage/logs/*.log`用户组和用户都是`root`，还有一个更诡异的的用户`82`，如下：
```
$ ls ./app/api_service/storage/logs/ -al
total 468
drwxrwxrwx 2 levi levi   4096 Jun 23 01:38 .
drwxrwxrwx 6 levi levi   4096 Jun 22 21:49 ..
-rwxrwxrwx 1 levi levi     14 Jun 22 21:36 .gitignore
-rwxrwxrwx 1   82   82  62998 Jun 22 21:49 laravel-2022-06-22.log
-rwxrwxrwx 1 root root 393537 Jun 23 01:45 laravel-2022-06-23.log
```
这样每天打开`laravel`项目会出现没有权限的502错误，需要手动将日志重新归属目录，或者设置权限
```
$ sudo chown -R levi:levi ./app/api_service/storage/logs/
# or
$ sudo chmod -R 0777 ./app/api_service/storage/logs/
```
但是第二天依旧会出现权限问题，请问要怎么解决这个问题呢？

**Comment by khs1994** [comment]
* https://github.com/docker-library/php/blob/master/8.1/alpine3.15/fpm/Dockerfile#L32

82 是 fpm 产生的，也就是通过网页访问产生的
root 是通过 cli 产生的 ./lnmp-docker php8-cli php artisan ...

**Comment by cgfeel** [comment]
> * https://github.com/docker-library/php/blob/master/8.1/alpine3.15/fpm/Dockerfile#L32
> 
> 82 是 fpm 产生的，也就是通过网页访问产生的 root 是通过 cli 产生的 ./lnmp-docker php8-cli php artisan ...

我明白了，我的`log`目录权限是`0755`(`drwxr-xr-x`)，当其他用户组出现错误写入`log`的时候，是不允许写入数据的，于是就报错了，我把`log`目录改成`0777`就好了

---

只是我有一点不明白，单独设置一个`82`的用户我能理解，为何不将`82`的用户组设置为`docker`，因为如果我当前的用户组要执行`docker`，就必须加入`docker`用户组；当我个人用户，和`82`这个用户都属于`docker`用户组时，我可以将目录权限设置为`0775`(`drwxrwxr-x`)，这也算是保留最后一点的安全
