### ISSUE TITLE
[反馈] 大家可以反馈一下对 Docker 的了解程度吗？

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#15]
* 完全不知道 `Docker` 是个什么东西

* 听说过，没实际使用过

* 会一些基本的操作（例如 `$ docker run`），但不知道 `Docker Compose`

* 会一些基本的操作，用过 `Docker Compose`

* 集群方面的 `Swarm mode` `k8s` 了解多少

如果可以的话，请附上您使用 `Docker` 的操作系统，`PHP` 版本 ，`网站服务器`（`NGINX` 或 `HTTPD` 等） ，方便我后续针对大家使用情况优化项目

* Windows

* Windows(使用 Linux 虚拟机)

* macOS

* Linux(Deepin、Ubuntu、Fedora,etc)

**Comment by khs1994** [comment]
会一些基本的操作（例如 docker run），了解 Docker Compose macOS

**Comment by khs1994** [comment]
会一些基本的操作（例如 docker run），了解 Docker Compose Linux(Deepin)

**Comment by liuzhaowei55** [comment]
会一些基本的操作，docker compose 也是用了你这个lnmp环境才知道的，用的是 mac ，看你写的这些命令还是挺吃力的，比如 demo 里那个redis，我就没看懂为什么 host 那个地方写一个 redis就可以了，而不用写一个地址

**Comment by khs1994** [comment]
你这个是典型的新手问题，哈哈，一会给你解答！

**Comment by liuzhaowei55** [comment]
@khs1994 哈哈，谢啦，我主要是用来做 Laravel 的本地开发环境，替代以前用的 homestead。

**Comment by khs1994** [comment]
`$ docker run --link` 了解吗？

`Redis` host 你认为该怎么写，写 IP 比如 `127.0.0.1` `localhost`? 我觉得你应该知道这肯定是错误的！

写 Redis 容器 IP ? 每次容器启动的 IP 不是固定的！怎么写？

`Redis` host 里的 redis 其实是 docker-compose.yml 里的服务名，当使用 docker compose 来启动多个容器时，它会在每个容器内部写入 host 。（/etc/hosts）

**Comment by khs1994** [comment]
你知道 /etc/hosts 文件的作用吗？
如果不知道，你应该知道 DNS 吧？

举个例子，平常要访问百度，我们输入的都是字符 `www.baidu.com` ,没人输入 IP 来访问百度吧。

这里同理，要连接 Redis server 我们平常都是输入 IP，由于容器 IP 不固定，我们只能用字符来代替。

**Comment by liuzhaowei55** [comment]
你这样讲我就明白了，我看`redis`更像是一个 env 的变量名，所以在想我的程序是怎么去获取这个变量的值的。我要再去看看，dockerfile，dcoker compose 配置文件的文档了

**Comment by liuzhaowei55** [comment]
你这样讲我就明白了，我看`redis`更像是一个 env 的变量名，所以在想我的程序是怎么去获取这个变量的值的。我要再去看看，dockerfile，dcoker compose 配置文件的文档了

**Comment by khs1994** [comment]
https://docs.docker.com/engine/tutorials/networkingcontainers/#add-containers-to-a-network

**Comment by khs1994** [comment]
不是 ENV

只是 /etc/hosts

其实也不用理解，你只要知道这样设置就行。

**Comment by liuzhaowei55** [comment]
@khs1994 Hi,我最近一直是在本地用你的这个项目在做开发，我现在准备在服务器上部署测试下，关于composer，jobs，cron这些命令行工具该怎么使用，还是在宿主机里配置吗？

**Comment by khs1994** [comment]
感谢您的使用

`composer` ,`git` 集成在了php镜像里。

计划任务在宿主机里执行吧，数据文件不都挂载出来了吗

**Comment by khs1994** [comment]
你没有使用过 `./lnmp-docker.sh composer` 吗？

**Comment by khs1994** [comment]
`bin/composer test --version`  `test` 指 `./app/test` 路径，以此类推

**Comment by khs1994** [comment]
生产环境方面我考虑更多的是 git 提交代码，服务器自动部署代码。

**Comment by liuzhaowei55** [comment]
宿主机执行计划任务的话就需要在宿主机安装php，同时mysql，redis的端口也要映射出来使用了

**Comment by liuzhaowei55** [comment]
git 我是倾向于安装到宿主机，我平时使用deployer.org做部署，虽然要在客户端主动操作，但是可以代码回滚之类的更放心一点

**Comment by khs1994** [comment]
看个人喜好吧，git 放在容器里执行，我主要为了 CI/CD

**Comment by khs1994** [comment]
计划任务和端口有什么关系？

**Comment by liuzhaowei55** [comment]
计划任务里的代码要去操作数据库

**Comment by khs1994** [comment]
docker exec 执行命令可以吗？

**Comment by khs1994** [comment]
计划任务执行比如 `mysqldump` 等备份命令？

**Comment by liuzhaowei55** [comment]
可以的，我去试了`docker exec`命令，可以在宿主机中执行了

**Comment by khs1994** [comment]
我建议你 Fork 一份我的代码，自己进行二次修改

**Comment by liuzhaowei55** [comment]
有，我打开了opcache，现在在看怎么配置 disable_function

**Comment by khs1994** [comment]
`opcache` 必须和 `xdebug` 扩展配合？

**Comment by liuzhaowei55** [comment]
不需要啊，为什么这么问？

**Comment by khs1994** [comment]
我不了解这个扩展，刚才看错了，你以后有什么需要增加的 PHP 扩展，到 issue 提出来。

**Comment by khs1994** [comment]
昨天忘了，用 `docker-compose exec 服务名` 进入容器，用 `docker exec` 还得查看容器名。

**Comment by qiuyimo** [comment]
会一些基本的操作（例如 docker run），了解 Docker Compose，macOS

本项目这么优秀, 我会时刻关注, 发现错误了就得纠正啊.

**Comment by khs1994** [comment]
生产环境不用列出了，什么原因你知道，哈哈！

**Comment by khs1994** [comment]
这个 issue 仅收集大家的相关信息，其他问题请另开 issue
