### ISSUE TITLE
[反例] Docker 最差实践

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#169]
* #157 使用 `--links` 参数

**Comment by khs1994** [comment]
#157 使用 `--links` 参数

**Comment by khs1994** [comment]
* `Dockerfile` 使用 `MAINTAINER` 指令

* https://github.com/laradock/laradock/blob/c4aef8e901a867a57df0b1aadf1c872165e65295/nginx/Dockerfile#L3

https://docs.docker.com/engine/deprecated/#maintainer-in-dockerfile

**Comment by khs1994** [comment]
* 一个容器包含 `N` 个服务（一个镜像安装了 `N` 个服务）

**Comment by qiuyuhome** [comment]
可以动态配置的没有给出说明,  在网上找了几个 docker 搭建 lnmp 的项目, 运行起来都报错, 基本都是代理的问题, 在不就是加速仓库的问题, 导致安装包找不到.

**Comment by khs1994** [comment]
我日前写了如何 `兼顾` 本项目升级和动态配置的问题，请查看文档：

* https://github.com/khs1994-docker/lnmp/blob/master/docs/config.md

有问题请到下面讨论

* https://github.com/khs1994-docker/lnmp/issues/238

**Comment by khs1994** [comment]
快速入门是简化版配置，如果你有兴趣持续使用本项目，那么请查看我给出的文档。

有任何问题都可以反馈。

**Comment by khs1994** [comment]
* 除了 `NGINX` 为了支持 TLSv1.3 和 `PHP` 需要自定义的太多，其他镜像尽可能的采用官方仓库的镜像

* 拉取镜像缓慢的问题，请务必配置 Docker 镜像

**Comment by khs1994** [comment]
* 使用 `latest` 标签

```bash
# this command is bad

$ docker run -it --rm nginx

# this command is good

$ docker run -it --rm nginx:1.13.12-alpine
```
