### ISSUE TITLE
[tips] Docker 化 PHP 项目最佳实践

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#187]
* 项目位于 `./app/demo`

* https://github.com/khs1994-docker/php-demo

**Comment by khs1994** [comment]
项目位于 `./app/demo`

**Comment by shangdev** [comment]
执行 `composer create-project khs1994/example:dev-master example`时提示：
![image](https://user-images.githubusercontent.com/15621520/44620651-c3677e80-a8ca-11e8-9195-723eca490aad.png)

**Comment by khs1994** [comment]
只支持最新版本 7.2.看你的版本7.1 直接克隆 git 吧

**Comment by khs1994** [comment]
还有文档有点旧了，我白天再更新一下，你感兴趣的话，稍后再看
