### ISSUE TITLE
监控方面讨论

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#266]

**Comment by qiuyimo** [comment]
如果你说的是服务器监控, 推荐使用 promethues, 我公司在用. 感觉很不错. 配合 grafana 的 UI, 显示效果很漂亮. 

放一个图出来看看效果. 
![image](https://user-images.githubusercontent.com/17526777/37562911-8bbed6b2-2aae-11e8-9671-bd3e34f7ff65.png)

![image](https://user-images.githubusercontent.com/17526777/37562919-bf188bb6-2aae-11e8-8950-8f7b72eefb04.png)
