### ISSUE TITLE
Ctrl + c can't stop command lnmp-php

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#280]
### 操作系统

* [x] macOS

### Docker 版本

* [x] Stable (v17.12)

### 问题描述

使用命令 `lnmp-php` 执行 php 脚本, 按 `ctrl + c` 无法停止进程.

这个有什么好的办法解决么?

**Comment by khs1994** [comment]
`-S` 启动服务器？还是执行脚本？

**Comment by qiuyimo** [comment]
执行脚本.

**Comment by qiuyimo** [comment]
因为是在容器里执行的脚本. 所以我在我的终端, 直接按 Ctrl + c, 是不能停止的.

**Comment by qiuyimo** [comment]
感觉这个在开发过程中, 非常的不方便.

**Comment by khs1994** [comment]
我调试一下，稍后回复

**Comment by khs1994** [comment]
暂时解决不了，命令行使用 docker 原始命令也停止不了

**Comment by khs1994** [comment]
已修复。

执行

```bash
$ ./lnmp-docker.sh update -f
```

升级到最新版

**Comment by khs1994** [comment]
https://github.com/moby/moby/issues/2838
