### ISSUE TITLE
Where dockerfile

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#286]
### 操作系统

* [x] macOS

### Docker 版本

* [x] Stable (v17.12)

### 问题描述

如何能看到你基础镜像的 dockerfile 文件? 

想学习一下. 怎么能看到啊? 项目里没有. 

hub 上也没有.

**Comment by khs1994** [comment]
https://github.com/khs1994-docker/lnmp/tree/master/dockerfile/php-fpm/7.2/alpine3.7
