### ISSUE TITLE
[反馈] LNMP 基础技能

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#459]
复制以下内容，将 不了解 不知道 的基础技能，复制到回复框，进行反馈

```bash
* [x] nginx `include` 指令包含其他配置文件
```

**Comment by qiuyuhome** [comment]
* [ ] docker `networks` 为什么在 php 的代码中, 连接数据库, 使用的 `host` 是 mysql. 我知道可以使用 mysql 容器内部的 ip, 但是为什么填写 `mysql` 就能代替呢?

**Comment by khs1994** [comment]
这个涉及到 Docker 的实现，只要知道怎么用就行了，没必要深究。
