### ISSUE TITLE
Support k8s.gcr.io gcr.io local server，Docker for desktop run kubernetes

### ISSUE THREAD

**Issue by khs1994** [khs1994-docker/lnmp#520]
gcr.io 国内访问有问题，所以我们开启一个 local server，让 Docker 桌面版从本地拉镜像

* 文档 https://github.com/khs1994-docker/lnmp/blob/master/docs/kubernetes/docker-desktop.md

添加如下 hosts

```bash
# 路由器分配给电脑的 IP gcr.io k8s.gcr.io
# 例如

192.168.199.100 gcr.io k8s.gcr.io
```

# 启动

首先关闭本地监听 443 端口的程序

```bash
$ ./lnmp-docker gcr.io

$ lnmp-docker gcr.io logs
```

执行完毕之后，Docker 设置中开启 k8s

开启成功之后，删除启动的 local server 容器

```bash

$ lnmp-docker gcr.io down

```

**Comment by lovese** [comment]
after this setup , How to install kubernetes dashboard???

**Comment by khs1994** [comment]
```bash
$ kubectl apply -f kubernetes/coreos/addons/dashboard.yaml
```

**Comment by lovese** [comment]
@khs1994 不用设置，可以直接调用k8s的接口吗？

**Comment by khs1994** [comment]
```bash
$ ~/.kube/config
```
已经自动生成好了，直接用 `kubectl` 就行。

```bash
$ kubectl get all -n kube-system

service/kubernetes-dashboard   NodePort    10.97.248.32   <none>        443:30508/TCP   3h
```

浏览器打开 `https://127.0.0.1:30508` 就可以了(提示证书错误，直接跳过就行)，端口号这里是例子，实际是多少自己看

**Comment by khs1994** [comment]
安装 k8s 的时候需要，启动成功了就不需要了。

然后 kubernetes/coreos/addons 里的 yaml 文件我都把 gcr.io 的镜像替换成了 docker hub 中的镜像，具体对应关系请看这个项目 https://github.com/anjia0532/gcr.io_mirror

以后你把 yaml 文件中的 gcr.io 镜像替换成 https://github.com/anjia0532/gcr.io_mirror 这里的镜像

> 这个翻译机器人是我开发的一个 CI 项目，关闭功能暂时没有

**Comment by lovese** [comment]
@khs1994 好的，谢谢了！

**Comment by lovese** [comment]
@khs1994 请问这个怎么办，访问不了
![image](https://user-images.githubusercontent.com/13268438/45529981-d959c680-b81a-11e8-8ec1-1f77fdfc38f2.png)

**Comment by khs1994** [comment]
访问 dashboard ？

我在 Chrome 试了一下，重新加载 左边有一个高级按钮，点一下，有 `继续前往的选项`，不知道为何你这里没有

其实还有一种方法，不过麻烦一点

```bash
$ kubectl proxy
```
浏览器打开 http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/45531367-0b225b80-b822-11e8-986c-3ec5e1e7ca20.png)
chrome://flags 我这样设置就可以了，你的不会这样可能是你的chrome不是最新版

**Comment by lovese** [comment]
@khs1994 
![image](https://user-images.githubusercontent.com/13268438/45531706-8afcf580-b823-11e8-8940-26a506b46efa.png)
这里是添加配置文件嘛？没找到配置文件  `~/.kube/config`

**Comment by khs1994** [comment]
跳过就行，也可以按照 https://github.com/khs1994-docker/lnmp-k8s/blob/master/docs/addons/dashboard.md 生成 token 或配置文件

**Comment by lovese** [comment]
@khs1994 
![image](https://user-images.githubusercontent.com/13268438/45532251-eb8d3200-b825-11e8-8307-a8a8b323398c.png)
我的是win 10 系统，命令不对

**Comment by khs1994** [comment]
把命令拆开，执行吧，要不用 WSL (下载 kubectl https://github.com/khs1994-docker/kubectl-cn-mirror 把 .kube 复制到家目录)

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/45532432-9dc4f980-b826-11e8-9da6-51eccd1691a7.png)
是要取这个字段嘛？

**Comment by lovese** [comment]
@khs1994 我登陆了，再次谢谢您！
