### ISSUE TITLE
lnmp-command 报错: unknown flag: --mount

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#539]
在终端执行以下命令生成错误报告

```bash
$ cd lnmp

$ ./lnmp-docker.sh debug
```

<details>

<summary>OS Environment Info</summary>

<code>

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</code>

<code>Docker version 1.13.1, build 94f4240/1.13.1</code>

<code>docker-compose version 1.20.1, build 5d8c71b</code>

</details>

<details>

<summary>Console output</summary>

<pre>

INFO   Use LNMP CLI in LNMP Root /root/docker/lnmp

INFO   .env file existing

INFO   ARCH is Linux x86_64

INFO   Docker version 1.13.1, build 94f4240/1.13.1

INFO   docker-compose v1.20.1 already installed Correct version

</pre>

</details>

### docker lnmp 环境应该是正常的. 但是使用 lnmp-command 失败. 

> ~/.bash_profile

```bash

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

# docker-lnmp
export LNMP_PATH=/root/docker/lnmp
export PATH=$LNMP_PATH:$LNMP_PATH/bin:$PATH
```

### 出现的问题

我这里使用 `lnmp-php` 和 `lnmp-composer`, 都会报错. 

```shell
[root@iZm5eat7o13nmw3p7hg674Z lnmp]# lnmp-php -v
unknown flag: --mount
See 'docker run --help'.
[root@iZm5eat7o13nmw3p7hg674Z lnmp]# lnmp-composer
+++ dirname /root/docker/lnmp/bin/lnmp-composer
++ cd /root/docker/lnmp/bin
++ pwd
+ DIR=/root/docker/lnmp/bin
+ source /root/docker/lnmp/bin/.arch
+++ uname -m
++ ARCH=x86_64
+++ uname -s
++ OS=Linux
++ VERSION=7.2.6
++ export TAG=7.2.6-alpine3.7
++ TAG=7.2.6-alpine3.7
++ '[' x86_64 = armv7l ']'
++ '[' x86_64 = aarch64 ']'
++ '[' x86_64 = x86_64 ']'
++ export DOCKER_IMAGE=khs1994/php-fpm
++ DOCKER_IMAGE=khs1994/php-fpm
+ docker run -it --rm --mount type=bind,src=/root/docker/lnmp,target=/app,consistency=cached --mount src=lnmp_composer_cache-data,target=/tmp/cache --entrypoint /docker-entrypoint.composer.sh khs1994/php-fpm:7.2.6-alpine3.7 composer
unknown flag: --mount
See 'docker run --help'.
[root@iZm5eat7o13nmw3p7hg674Z lnmp]#
```

### 疑惑
我之前用的是 zsh, 换回了 bash, 不知道是否有影响. 

### 希望指点一下
我应该怎么做, 才能使用 lnmp-command .

**Comment by khs1994** [comment]
版本太旧，参考 https://github.com/yeasy/docker_practice/blob/master/install/centos.md 进行安装。

**Comment by qiuyimo** [comment]
#### 按照 https://github.com/yeasy/docker_practice/blob/master/install/centos.md 的方案, 完美解决. 

期间忘了删除原来的镜像, 结果出了点误差, 

使用 `docker system prune -a` 之后再启动 `./lnmp-docker.sh up`, 完美解决. 

#### 谢谢 khs1994 😁
