### ISSUE TITLE
How to connect mysql？

### ISSUE THREAD

**Issue by shangdev** [khs1994-docker/lnmp#596]
我使用wordpress系统，进行项目的安装，需要输入数据库信息：
数据库名、用户名、密码、主机

其中用户名是root，密码默认是test，主机我填127.0.0.1

但是无法连接数据库，提示用户名或者密码错误。所以主机那里应该填啥？

还有就是我看文档里写的需要暴露8080端口，我已经在腾讯云控制台那里开放了8080端口，但是还是无法访问phpmyadmin服务，问了客服，她说把监听的端口改成0.0.0.0试试、、这是正确的方法吗？

**Comment by khs1994** [comment]
其中用户名是root，密码是mytest，主机填 mysql

**Comment by khs1994** [comment]
编辑 .env 文件

```bash
# LNMP_PHPMYADMIN_PORT=127.0.0.1:8080

LNMP_PHPMYADMIN_PORT=0.0.0.0:8080
```

把 phpmyadmin 暴漏到公网注意风险

**Comment by shangdev** [comment]
@khs1994 

我降级了mysql到5.6.41在.env里，

现在报错信息如下，和以前的一个[issue](https://github.com/khs1994-docker/lnmp/issues/543)一样：
![image](https://user-images.githubusercontent.com/15621520/44952844-45076f80-aebc-11e8-95ef-8338e91aecd8.png)

我用里边的办法删除数据卷，提示以下错误：
![image](https://user-images.githubusercontent.com/15621520/44952838-2d2feb80-aebc-11e8-8176-614a2d2a012a.png)

这个怎么破解、、

**Comment by khs1994** [comment]
删除数据卷加 `-v` 参数
 
```bash
$ lnmp-docker down -v
```

图里的报错是因为 mysql 容器没有起来，你先前运行的 8.0 版本，之后你又回退到 5.6 ，数据不兼容，所以 mysql 容器没有起来。

先把数据卷都删了，然后再启动

**Comment by shangdev** [comment]
我是这样操作的：
`
# ./lnmp-docker down -v
# docker volume rm lnmp_mysql-data
# ./lnmp-docker up
`

但是mysql还是启动不了、、其他可以正常启动

你说的删除数据卷应该是指mysql的数据卷吧、

**Comment by khs1994** [comment]
也许是 8.0 与 5.6 的配置文件不兼容？把 mysql 容器日志贴一下吧

```bash
$ docker container ls -a

$ docker container logs mysql容器ID
```

日志在 `logs/mysql/error.log`

**Comment by shangdev** [comment]
![image](https://user-images.githubusercontent.com/15621520/44953052-5783a800-aec0-11e8-8c95-82526371a2b3.png)

好像是这样的，运行 ./lnmp-docker up 时mysql 可以启动，但是一访问就自动关闭了、、

**Comment by khs1994** [comment]
`config/mysql/docker.cnf`

```bash
log_timestamps=SYSTEM
```

把这个配置项注释掉

**Comment by shangdev** [comment]
现在好了、难道是mysql5.6.41不支持这个变量吗、、

**Comment by khs1994** [comment]
刚查了一下 5.7 新增的，解决 mysql 时间与系统时间不同步的，配置项上边有链接，详情自己看吧。
