### ISSUE TITLE
Database MySql: Error establishing a database connection！

### ISSUE THREAD

**Issue by shangdev** [khs1994-docker/lnmp#599]
debug 晚上补上，现在登不上服务器、、

我把默认的8版本切换到了5.6版本、
后台提示：Warning: mysqli_select_db(): MySQL server has gone away in /app/missxiong/wp-includes/wp-db.php on line 1024

容器没有异常退出，只是间歇性提示无法连接！

**Comment by khs1994** [comment]
容器没有异常退出？只是间歇性的提示连接不上？

**Comment by khs1994** [comment]
原因是 MySQL 连接时间过长，查看一下慢日志，调试一下

```bash
$ lnmp-docker mysql-cli

$ cd /var/lib/mysql

$ ls -la *-slow.log
```

或者修改 mysql 配置，增长超时时间

```bash
wait_timeout=2880000
interactive_timeout = 2880000
```

**Comment by shangdev** [comment]
@khs1994 
![image](https://user-images.githubusercontent.com/15621520/45729684-2f09e680-bc00-11e8-9f19-f4e573598598.png)
上面这些数据是错误信息吗?

还有我查了下Query_time，有几个语句确实时间比较长：
![image](https://user-images.githubusercontent.com/15621520/45729778-aa6b9800-bc00-11e8-9cc7-2c65d6787783.png)

**Comment by shangdev** [comment]
然后我查了一下具体的语句：
![image](https://user-images.githubusercontent.com/15621520/45729840-fcacb900-bc00-11e8-8be0-2315a1fb480e.png)

不应该啊，，就一个select、、、还指定了field

**Comment by shangdev** [comment]
@khs1994 
![image](https://user-images.githubusercontent.com/15621520/45750257-e45c8e80-bc40-11e8-8ac8-1dc2967f89bc.png)
我准备导出debug时，好像并没有lnmp-docker.sh这个脚本、、

**Comment by khs1994** [comment]
不用 debug 了，问题就是数据库有些语句执行慢。

**Comment by shangdev** [comment]
@khs1994 
![image](https://user-images.githubusercontent.com/15621520/45760628-18de4380-bc5d-11e8-8724-116fa6e730ab.png)
我在phpmyadmin里执行里这条语句，，查询相当快的，，不会耗费那么久、

**Comment by khs1994** [comment]
机器性能怎么样

**Comment by shangdev** [comment]
@khs1994 
解决了，是wordpress系统插件的问题，还不清楚原因，但是把插件卸载了重装了一遍就好了、、
麻烦关一下这个issue。
