### ISSUE TITLE
How do i install the supervisor?

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#603]
项目使用了supervisor，请问怎么装呢？还是自己在这个包里创建一个镜像？

**Comment by khs1994** [comment]
需要用 supervisor 管理什么程序。

PHP,还是需要运行多种程序。

**Comment by lichnow** [comment]
@khs1994 管理laravel的任务列队的，这个是laravel程序必装的啊，还有就是node不支持，如果要自动构建前端就很麻烦了，提个建议，尽量代码结构清晰一点(比如把.sh去掉什么的)，类似 [lnmp-docker](https://github.com/bravist/lnmp-docker) ,这样的结构,方面二次开发哦，这样推广一下star会直接上去，现阶段版本很难进行二次开发  ^V^

**Comment by khs1994** [comment]
`supervisord`  已经加上了。

`lnmp-npm` 解决不了问题吗？把命令写到 `package.json` 的 `scripts` 字段，运行 `lnmp-npm run xxx`。

**Comment by lichnow** [comment]
@khs1994 `lnmp-npm`解决问题很给力，而且不知道你做了什么优化处理，在生成环境测试laravel，比其它已有类似集成包(或者自己写的)速度快很多,甚至超过宿主机直接搭建的lnmp，尤其是k8s集群甚至drone的ci和di都整合了。但是有一个非常大的问题，就是代码太过黑盒，自定义修改非常困难，直接用于公司应用有点担心。这里只是提一个小建议，把代码和结构做成清晰化,透明化(就是不需要这么多变量和嵌套还有自定义的sh命令，以及简单易懂的文件结构,k8s与docker的基本配置分离,松耦合等)，方便企业或个人自定义修改,可以做收费的授权,但是黑盒比收费授权开源更不好推广。比如，我想使用drone，就只能看着文档案例一步步尝试，无法直接看代码就可以搞起。想添加一个gogs，那么具体在compose.yml,还是compose_override.yml里面添加，想添加一个nest.js的环境，docker应该放在哪里合适，微服务怎样在里面集成这些问题还是挺大的。现阶段生成环境还是在使用lnmp-docker，比较好自定义，但是非常期待你的lnmp的后期版本。

**Comment by khs1994** [comment]
lnmp-docker 脚本主要执行一些初始化动作。

比如事先建立好日志文件，mysql 启动时如果日志文件不存在，那么就不能启动。

再就是把示例配置文件复制一份。

速度快的话，应该是你的错觉。你使用的是 macOS?

**Comment by khs1994** [comment]
再就是脚本 `lnmp-XXX` 把一系列 `docker run XXX` 命令封装了一下。具体源码都能看到，也没有复杂的 shell 语法。有 shell 基础的都能看懂的。

**Comment by khs1994** [comment]
macOS 的话在 volumes 加上 `cached` 指令的话，确实速度上有提升。

* https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-for-mac

`docker-cluster.xxx` 这是使用 Docker Compose 启动集群用的和 `docker-compose.yml` 一个意思。

文档里有介绍 https://github.com/khs1994-docker/lnmp/tree/master/docs/clusterkit

**Comment by lichnow** [comment]
@khs1994 明白了，谢谢耐心解答，好人啊，哈哈
