### ISSUE TITLE
What if git updates ignore changes after custom configuration

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#605]
```
5. 建议通过 git 管理 ./config/nginx.my 文件夹，我们以后就在 nginx.my 文件夹内新增 NGINX 子配置文件（请参照 nginx 文件中的示例配置），HTTPD 同理
```
对于这段话有点难理解，通过git管理，是指直接在.gitignore中添加自定义的配置文件吗？还是怎么做？下次pull下来代码变更如何忽略？

**Comment by khs1994** [comment]
用户自己在 `config` 文件夹新增的文件夹默认都被 .gitignore 排除了，所以每次更新本项目，不会对你的自定义配置文件有任何影响。

**Comment by lichnow** [comment]
@khs1994 也就是`建议通过 git 管理 ./config/nginx.my 文件夹`这句话我根本不需要管对吗？如果是这样的情况，把`用户自己在 config 文件夹新增的文件夹默认都被 .gitignore 排除了，所以每次更新本项目，不会对你的自定义配置文件有任何影响。`这句话加进文档里比较好^V^

**Comment by khs1994** [comment]
文档的意思是你可以在 `nginx.my` 中通过 `git init` 在此目录中初始化一个 git 仓库，通过 git 管理配置文件。这两个 git 相互独立。

这算是一种备份配置文件的方式。

**Comment by lichnow** [comment]
@khs1994 额，大神，你得写清楚啊，现在明白了，这文档太晦涩了，哈哈，还有一个问题，nginx启动了,如果启动httpd也就是apache,那么nginx可以直接代理php-fpm也可以选择代理httpd来运行php了吗？也就是php-fpm和httpd两个不同的容器可以共存，按需使用了？

**Comment by khs1994** [comment]
nginx 代理 httpd？没考虑到 nginx 和 httpd 同时启动的情况。nginx 和 httpd 监听的端口一样，你如果这样做的话，先在 .env 文件中把端口修改一下

**Comment by lichnow** [comment]
@khs1994 ok,明白了，还有一些关于环境变量的问题，等等重启一个issue

**Comment by khs1994** [comment]
文档有哪些不理解，可以提出来。
