### ISSUE TITLE
Problems with changing mysql passwords

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#606]
```
如果原来启动过，要么销毁（数据卷）之后重新启动，要么手动进入命令行修改密码
```
对于这段话比较难理解,具体问题

1. 如果我需要改Mysql密码，必须把数据销毁(也就是删除所有已有数据)吗？
2. 具体如何销毁数据卷,是指用`docker-composer build`命令重新构建吗？
3. 所谓的数据卷就是与宿主机共享的那个数据文件夹吗？

**Comment by khs1994** [comment]
1. 你启动过一次，mysql 容器的初始化脚本就不会设置密码了。所以需要自己登录到 MySQL 改密码
2. 销毁数据卷和 docker-composer build 没关系
3. 数据卷用 docker volume ls 查看，以 lnmp-* 开头的就是本项目所使用的数据卷，你用 docker volume rm 数据卷名来删除，注意数据备份。

我的建议是自己登录到 MySQL 改密码。

**Comment by lichnow** [comment]
@khs1994 也就是直接自己登录到Mysql用命令改密码然后重启，或者直接phpmyadmin修改就可以了，跟数据卷关系不大，是这样吗？

**Comment by khs1994** [comment]
可以的。
