### ISSUE TITLE
About a long-term paid partnership.

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#607]
这两天一直在测试你的程序，向公司老板建议后，得到回复，希望能建立长期合作关系。
> 我们是一家云计算方案服务公司，现阶段采用的产品是基于cloudstack二次开发的云系统，其中包含很多类似社交电商，微信电商等自主研发的产品。鉴于目前许多客户建议需要提供容器化集群以及我们未接触过的docker,k8s等方案，类似rancher等。
现阶段在逐步试用你开发的集成包，功能十分强大(当然文档和结构方面确实还有些问题),等试用测试通过后，希望能与你建立一个长期良好的合作关系。

现阶段我们商量的方案
1.赞助你研发资金(老板说在百万/年范围内),你提供及时快速的版本轶代，以及提供完整齐全的文档和及时的技术反馈，并建立官网和社区，我们负责帮你推广，社区首页需要挂上我们的LOGO等信息
2.收购方案，一次性支付你一笔客观的费用，需要一个更加完善，结构清晰易懂，文档清楚的应用。我们负责开发web管理界面，负责运营等，每年再支付你额外的升级以及维护费用直到我们可以完全接手自行二次研发

以上只是转达我的loader的意思，如果觉得引起你的不适，当没看到，我直接删除，不影响这个软件的开源环境，如果有兴趣方便提供一个微信吗？

ps: 我还在试用，可能要有问题，这个如果没兴趣当没看到哈^V^

**Comment by khs1994** [comment]
我可以在我力所能及的范围内提供技术支持。

如果本项目对你们有价值，可以考虑打赏。https://zan.khs1994.com

不限制做二次开发，你们可以随意修改。

> PS 感觉本项目没有那么大的商业价值，具体联系可以通过邮件 khs1994@khs1994.com

**Comment by lichnow** [comment]
@khs1994 OK，明白你的意思了，加油，大牛，有问题继续请教你哦
