### ISSUE TITLE
How khs 1994-docker / ci and lnmp-dcocker integrate

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#609]
如果我需要gogs,drone和lnmp-docker运行在一台服务器，请问如何整合呢？

**Comment by khs1994** [comment]
drone 的 README 已更新。请切换到 18.09 分支查看。

**Comment by lichnow** [comment]
@khs1994 是这个吗？[https://github.com/khs1994-docker/lnmp/blob/18.09/README.cn.md](https://github.com/khs1994-docker/lnmp/blob/18.09/README.cn.md),没有drone相关内容啊

**Comment by khs1994** [comment]
https://github.com/khs1994-docker/lnmp/tree/18.09/drone

**Comment by lichnow** [comment]
@khs1994
 
1.`php-demo`最佳实践的文档也会更新是吗？
2.这样弄好后也就是以后要ci和di的服务器分开就在DI服务器安装`docker-lnmp`的时候排除`Drone`就行了,在CI服务器上还是单独安装[docker-ci](https://github.com/khs1994-docker/ci)这个,如果是web应用和CI(gogs,drone)应用放一个服务器，就直接在`docker-lnmp`中加上`drone`的配置就可以了，是这样理解吗

**Comment by lichnow** [comment]
@khs1994 看错了文档，看的还是`master`的，看了新文档后懂了
