### ISSUE TITLE
What does " $ { lnmp _ nginx _ https _ port : -0.0.0.0 : 443 } : 443 " mean?

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#610]
请教一个问题
`"${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443"`这个什么意思啊，我自己这边设置默认值是这样的
`"${NGINX_HTTPS_PORT}:443"`

**Comment by lichnow** [comment]
@khs1994 `${NGINX_HTTPS_PORT}:443`这个是我自己写的一个简易包里的。。。
这里有两个问题不太明白，需要请教

#### 问题一
`${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443`这句话前面半段意思是`LNMP_NGINX_HTTPS_PORT` 变量未设置时，就取默认值 `0.0.0.0:443`，这个是明白的，后面再加个`:443`就不理解了。。。

用php的代码表示:
```
$port = LNMP_NGINX_HTTPS_POR  ?? '-0.0.0.0:443'
$port = $port :? '443'
```
也就是$port上面一段已经设置了，下面肯定是存在的啊，为什么还要做个(如果$port没设置则取443的)判断？

#### 问题二
端口号可以设置成`-0.0.0.0:443`的样式吗？

**Comment by khs1994** [comment]
前一个是宿主机端口，后边是容器端口

宿主机ip:宿主机端口:容器端口
