### ISSUE TITLE
Nginx cannot proxy phpmyadmin

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#618]
请在`docker-compose.yml`的`phpmyadmin`配置中添加
```
networks:
      - frontend
      - backend
```

在`lnmp/docker-compose.yml`和`lnmp/drone/docker-compose.yml`的`mysql`和`mariadb`的配置中都添加
```
networks:
      - backend
```

**Comment by khs1994** [comment]
NGINX unit 还是 NGINX

**Comment by lichnow** [comment]
@khs1994 在nginx里面代理phpmyadmin,因为phpmyadmin里面网络没设置，不能通信，修改后就好了，请把仓库里面的改掉吧
