### ISSUE TITLE
A process problem of combining drone with lnmp-docker

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#621]
我现在的.drone.yml里面创建的是一个php-fpm的image,通过drone构建之后会出现一个容器,但是默认lnmp-docker已经build了php-fpm这个镜像,好需要构建这个镜像吗？构建好之后发布到服务器启动镜像的容器,如果服务器上用的是lnmp-docker,本身就带有php-fpm,如果每个php应用也都是php-fpm镜像是否会引起端口方面的冲突的,请问具体这个问题能给点指导吗？谢谢啦

**Comment by khs1994** [comment]
假设有 N 个应用，我们会生成 N 个 php-fpm 镜像和 N 个 NGINX 镜像，你意思是怎么用本项目启动(管理)这么多的镜像？

> 答案，无解。生产环境使用容器的唯一解决办法就是使用 k8s。

或者把 N 个应用的代码打入一个 php-fpm 镜像 和 一个 NGINX 镜像，那么可以使用本项目。（我觉得你实际上肯定不想这么做，这样的话就是牵一发动全身，一个应用有改动，就得重新构建）。

我不太清楚你们公司需要怎么样容器化方案，是做公有云平台还是打包一个容器环境给客户。你可以举例子说明一下，不方便公开讨论的话，可以给我发邮件。

**Comment by lichnow** [comment]
@khs1994 我们公司原来是购买的xen架构系统，后来自己开发了一套kvm架构，可以自助开通虚拟机,然后通过虚拟机的方式实现集群，前几年刚刚换的cloudstack架设，其实仍然基于虚拟机方案，没接触过容器这一块，但是最近要增加到容器方案。原来给客户提供的CI方案(几乎称不上devops)是非常简单的，因为这方面需求比较低，基本就是提交到版本控制,然后gitlab发送webhooks,服务器直接写一个python脚本克隆更新。接着通过SSH分发到其它虚拟机，非常简单。现在需要开始尝试从k8s+drone+gitea这套简易现成的CICD方案来方便部署应用,客户自己的应用基本也是委托我们开发的php,node,python这几种,没有编译型的应用，但是学了半个月左右的docker，还是许多东西搞不清楚。

比如
一，如果一个应用就要开一个PHP-FPM或者egg.js的映射端口，那么一台服务器开很多个这种进程,而且得确保所有的应用容器的映射端口不一样，这比较难
二，如果一个应用不仅映射一个PHP-FPM或者express的端口，甚至直接打入Nginx，那么一台虚拟机就只能开一个应用了(因为一般应用硬性规定为80端口)，那么应用非常小是否也必须占据一台虚拟机呢？
三，如果直接使用lnmp-docker或者laradock的方式，与传统的lnmp基本无差别，那drone需要部署应该怎么做呢？drone完全是基于容器的,构建后直接在服务器端通过pull镜像启动容器来完成的部署的，完全没办法直接复制源代码到根目录啊，就算能复制，那还是走老路线了
四，k8s暂时无法入门(容器掌握还没到这个程度)，因为最近必须掌握和拿出来demo的是drone+gogs+linux部署多个php应用和Node应用。当然掌握k8s是好，但是我个人是写全栈应用的，对这个真的感觉非常难，短期不可能实现，所以真诚的请教有别的方法实现吗？

具体需求: gogs上传代码(已掌握)->drone测试并构建镜像(已掌握)->drone上传到私有的registry(还在摸索中)->drone根据.drone.yml登录服务器拉取镜像并创建启动容器(应该问题不大)->服务器启动的容器如何才能支持多个php-fpm或者Node(现阶段基本无解)

最后十分感谢你这些天对我的帮助和贡献出这么好的开源包(从包里学习到了很多,老大都说想要收购了,哈哈)
如果有空，还请您百忙之中帮我解惑以上几个问题，谢谢啦

**Comment by khs1994** [comment]
k8s 就是成熟的方案。虽然复杂，但肯定绕不过去。

你先在 Docker 桌面版尝试一下，https://github.com/khs1994-docker/lnmp-k8s/blob/master/docs/docker-desktop.md

k8s 中一个应用可以抽象为一个服务，然后为每个服务增加一条 ingress 规则来暴漏服务。

ingress 根据客户端来访域名来代理到不同的服务。

**Comment by lichnow** [comment]
@khs1994 从《Dorcker技术入门与实践》这本书上了解了一下原理，开始稍微能领会一点了，哈哈，晚点测试一下你的桌面版，谢啦
