### ISSUE TITLE
Automatic renew of acme.sh ssl certificates

### ISSUE THREAD

**Issue by shangdev** [khs1994-docker/lnmp#629]
还有就是请问如何续期，再运行一遍生成证书命令吗？

**Comment by shangdev** [comment]
@khs1994 

我用了 certbot，生成的证书放在 
/etc/letsencrypt/live/xx.cn/privkey.pem

然后直接在 nginx 配置文件里不能直接写这个路径吗？提示找不到文件。

**Comment by khs1994** [comment]
宿主机的文件没有挂载到容器中，在容器中当然找不到了。

你可以设置 cerbot 的生成目录到本项目的ssl文件夹内。

或者你可以同步这两个文件夹

**Comment by shangdev** [comment]
@khs1994 
我使用了软连接：
`ln -s /etc/letsencrypt/live /var/www/lnmp/config/nginx/ssl`

然后在site.conf中:
```
ssl_certificate conf.d/ssl/live/missxiong.cn/fullchain.pem;
ssl_certificate_key conf.d/ssl/live/missxiong.cn/privkey.pem;
```

显示错误：
```
nginx: [emerg] BIO_new_file("/etc/nginx/conf.d/ssl/live/missxiong.cn/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/conf.d/ssl/live/missxiong.cn/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

conf.d/ssl/live... 怎么会指向 /etc/nginx/conf.d/ssl/live...呢？

**Comment by khs1994** [comment]
软连接不行的！容器获取不到宿主机文件的！

**Comment by khs1994** [comment]
具体路径对应关系，https://github.com/khs1994-docker/lnmp/blob/master/docs/path.md

明天再回复

**Comment by shangdev** [comment]
@khs1994 
又用文档的方法重新生成了一遍，顺便报个错误：

![image](https://user-images.githubusercontent.com/15621520/49531102-8d3b9100-f8f4-11e8-8546-d6d5555f4e5f.png)

**Comment by khs1994** [comment]
哪个dns服务商？证书生成了吧？这个错误是移除dns记录出错，不影响证书生成

**Comment by shangdev** [comment]
@khs1994 
证书生成了，服务商是 DNSpod
