### ISSUE TITLE
Generate an error report at windows f's powershell terminal by executing the following command

### ISSUE THREAD

**Issue by will-nb** [khs1994-docker/lnmp#736]
在windowsf的powerShell终端执行以下命令发生错误

```bash
$ cd lnmp
$ ./lnmp-docker new
```

错误提示为：
```
不存在具有提供的名称的分布。
```
![image](https://user-images.githubusercontent.com/3499784/68600182-010af400-04dd-11ea-9934-43988567922f.png)

**Comment by khs1994** [comment]
这个命令需要 WSL ,WSL 安装了吗

**Comment by khs1994** [comment]
检查 `.env.ps1` `$DistributionName` 变量的值

```powershell
# $DistributionName="ubuntu-18.04"

$DistributionName="你的 wsl 发行版名称"
```

出现错误的原因是 `ubuntu-18.04` 这个 wsl 不存在

执行 `$ wsl -l` 可以看到安装的 wsl 发行版

**Comment by will-nb** [comment]
![image](https://user-images.githubusercontent.com/3499784/68670451-efcaf180-0587-11ea-8a00-bab036f22fed.png)
谢谢，装了ubuntu18.04,然后显示另一个报错了。
运行命令：
```
./lnmp-docker.ps1 new
```
报错：
```
/bin/bash: lnmp-docker: command not found
```

**Comment by khs1994** [comment]
pull 最新代码 `19.03` 分支,不是 `master` 分支
