### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by batcom** [khs1994-docker/lnmp#748]
<details>
<summary>OS Environment Info</summary>
<pre>

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

</pre>

<code>Docker version 19.03.3, build a872fc2</code>

<code>docker-compose version 1.24.1, build 85d94090</code>

* https://github.com/khs1994-docker/lnmp/commit/50218fa6c87679a8419cc4e957597f3c26c0a57c

</details>
<details>
<summary>Console output</summary>

<pre>

INFO   Use LNMP CLI in LNMP Root /home/pi/git/lnmp

INFO   Exec custom scripts

WARNING  Try lnmp-* commands? Please see cli/README.md

INFO   .env file existing

INFO   APP_ROOT is /home/pi/git/lnmp/app

INFO   Branch is 19.03

INFO   ARCH is Linux aarch64

INFO   Docker version 19.03.3, build a872fc2

INFO   docker-compose v1.24.1 already installed Correct version

INFO   development

INFO   Init is SUCCESS

Creating lnmp_phpmyadmin_1 ... done
Creating lnmp_mysql_1      ... done
Creating lnmp_redis_1      ... done
Creating lnmp_php7_1       ... done
Creating lnmp_nginx_1      ... done
INFO   Test nginx configuration file...

nginx: [emerg] host not found in upstream "php7" in /etc/nginx/conf.d/demo-include-php.config:10
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR  Nginx start error,please check config/nginx

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                             PORTS                                                                NAMES
8b9b89373c82        nginx:1.17.6-alpine             "nginx -g 'daemon of…"   18 seconds ago      Up 10 seconds (health: starting)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:10000->10000/tcp   lnmp_nginx_1
2fd75a403209        khs1994/php:7.3.11-fpm-alpine   "docker-php-entrypoi…"   33 seconds ago      Restarting (1) 5 seconds ago                                                                            lnmp_php7_1
ad695c602e90        mysql:8.0.18                    "docker-entrypoint.s…"   33 seconds ago      Up 1 second                        127.0.0.1:3306->3306/tcp, 127.0.0.1:33060->33060/tcp                 lnmp_mysql_1
682f98ca864b        redis:5.0.7-alpine              "docker-entrypoint.s…"   33 seconds ago      Restarting (1) 2 seconds ago                                                                            lnmp_redis_1
124c2825dc4e        phpmyadmin/phpmyadmin:latest    "/docker-entrypoint.…"   33 seconds ago      Up 3 seconds (health: starting)    127.0.0.1:8080->80/tcp                                               lnmp_phpmyadmin_1

</pre>

</details>

## My Issue is

执行 ./lnmp-docker up 出现找不到php7 upstream 然后其它所有镜像都一直是restarting中

**Comment by khs1994** [comment]
执行 `$ docker logs lnmp_php7_1` 贴上日志

**Comment by khs1994** [comment]
请问是在树莓派使用本项目吗？

将 `docker version` 执行结果贴出来。

mysql 镜像是你 pull 下来的？我实测在树莓派使用 `./lnmp-docker up` pull 不下来 mysql 镜像。
