### ISSUE TITLE
Commands such as 'lnmp-xxxx' cannot be used on windows 10

### ISSUE THREAD

**Issue by polichan** [khs1994-docker/lnmp#825]
<details> 
 <summary>OS Environment Info</summary> 

 <code>OS: 10.0.18362.628</code> 

 <code>Docker: Docker version 19.03.8, build afacb8b</code> 

 <code>Docker Compose: docker-compose version 1.25.4, build 8d51620a</code> 

 <code>LNMP COMMIT: https://github.com/khs1994-docker/lnmp/commit/afd3853845ed1dfb0820667a6ffe4f9f2d73cbff</code> 

 </details> 

 <details> 

 <summary>Console output</summary> 

  
  

 <pre>  
wslapth : 无法将“wslapth”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路
径正确，然后再试一次。
所在位置 C:\Users\ayden\lnmp\windows\lnmp-php.ps1:54 字符: 27
+   --mount type=bind,src=$(wslapth $PWD),target=/app `
+                           ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (wslapth:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: invalid mount config for type "bind": field Source must not be empty.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
  </pre> 

 </details> 

 <h2>My Issue is</h2> 
   

参考了此文章进行的安装：

[文章链接](https://docs.lnmp.khs1994.com/install/windows.html#%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

使用了 19.03 的 Docker 分支

在 Windows 10 上安装 Docker，但是在使用 `lnmp-php` 这种快捷的指令时，提示如上错误信息。刚开始我怀疑是没有安装 `windows subsystem linxu`的问题，于是我就在应用商店装了一个，但是发现还是没有办法使用。环境变量的配置也是按照文档中一步步来的，甚至连 `git clone` 的路径也是一样的。希望能予以解答，感激不尽。

**Comment by khs1994** [comment]
已经修复，请 pull `19.03` 分支。

> `wslapth` 应该是 `wslpath`
