### ISSUE TITLE
Dude, this isn't swoole and elastic search, is it?

### ISSUE THREAD

**Issue by moon-zhangyue** [khs1994-docker/lnmp#855]

**Comment by khs1994** [comment]
swoole 的例子请查看这里：

https://github.com/khs1994-docker/lnmp/blob/4e78acede088d3b4e06c0987263e4ec16bc11d3b/docker-lnmp.include.example.yml#L59

本项目是为了打造一个通用平台，不会内置过多的服务，你可以参考文档自行添加

* https://docs.lnmp.khs1994.com/custom.html#%E9%80%9A%E8%BF%87%E4%BF%AE%E6%94%B9-docker-lnmp-include-yml-%E6%96%87%E4%BB%B6%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9C%AC%E9%A1%B9%E7%9B%AE
